// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.Data;

namespace ToDoList.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoList.Entities.DayTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.HasKey("Id");

                    b.ToTable("DayTasks");
                });

            modelBuilder.Entity("ToDoList.Entities.TaskToDo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<Guid>("Day");

                    b.Property<Guid?>("DayTaskId");

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<TimeSpan>("TimeRequired");

                    b.Property<string>("Title")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("DayTaskId");

                    b.ToTable("TasksToDo");
                });

            modelBuilder.Entity("ToDoList.Entities.TaskToDo", b =>
                {
                    b.HasOne("ToDoList.Entities.DayTask")
                        .WithMany("Tasks")
                        .HasForeignKey("DayTaskId");
                });
#pragma warning restore 612, 618
        }
    }
}
